# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [5]:
import numpy as np
np.__version__

'1.26.4'

2) Создать нулевой вектор размера 10

In [7]:
zero_array = np.zeros(10)
zero_array, zero_array.shape

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,))

3) Создать вектор заполненный 7-ами размера 7

In [9]:
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [12]:
np.arange(10, 100+1, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [18]:

random_array = np.random.rand(10)
reversed_array = random_array[::-1]
print("Оригинальный массив:")
print(random_array)
print("Массив задом наперёд:")
print(reversed_array)

Оригинальный массив:
[0.4377583  0.27624133 0.16665057 0.91644823 0.21779696 0.3200629
 0.26458859 0.67556789 0.22514896 0.00802445]
Массив задом наперёд:
[0.00802445 0.22514896 0.67556789 0.26458859 0.3200629  0.21779696
 0.91644823 0.16665057 0.27624133 0.4377583 ]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [23]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [24]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [38]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, np.arange(1, 5))
matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [39]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [40]:
random_matrix = np.random.rand(10, 10)
row_means = np.mean(random_matrix, axis=1)
normalized_matrix = random_matrix - row_means[:, np.newaxis]
print("Оригинальная матрица:")
print(random_matrix)
print("Средние по строкам:")
print(row_means)
print("Нормализованная матрица:")
print(normalized_matrix)


Оригинальная матрица:
[[0.1590474  0.09710948 0.38624682 0.35725697 0.01138309 0.27193512
  0.15802755 0.73365104 0.58078181 0.15043696]
 [0.04218406 0.55293349 0.8452067  0.58959293 0.73326354 0.74100844
  0.90348854 0.93097441 0.50278118 0.85568092]
 [0.1548756  0.3287533  0.10532024 0.54420775 0.44375538 0.25610563
  0.11092192 0.24882714 0.11822389 0.99784073]
 [0.20386588 0.04790095 0.35617576 0.63869325 0.43959956 0.10056462
  0.94668782 0.82331789 0.50402438 0.18682162]
 [0.03563056 0.02410436 0.27182079 0.75041844 0.35053689 0.20203016
  0.94392005 0.74839908 0.99798449 0.81340616]
 [0.44441752 0.53944952 0.95141224 0.64244813 0.5404239  0.93150882
  0.46450517 0.35706253 0.50933681 0.17266897]
 [0.54642588 0.92640458 0.07711448 0.34802379 0.14737052 0.23758511
  0.67900869 0.17958193 0.74833695 0.27030974]
 [0.77744829 0.16678203 0.8473166  0.37880989 0.17759065 0.449647
  0.12668465 0.91113379 0.95791865 0.59193968]
 [0.59688981 0.72306716 0.02792019 0.19193983 0.21614641 0.3

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [41]:
random_matrix = np.random.rand(10, 10)
column_medians = np.median(random_matrix, axis=0)
normalized_matrix = random_matrix - column_medians
print("Оригинальная матрица:")
print(random_matrix)
print("Медианы по столбцам:")
print(column_medians)
print("Нормализованная матрица:")
print(normalized_matrix)


Оригинальная матрица:
[[0.09887839 0.71524902 0.97673003 0.06031358 0.55353207 0.14767774
  0.2698936  0.31638456 0.18934641 0.5044953 ]
 [0.83088302 0.48880626 0.20297753 0.53908514 0.33401615 0.41533863
  0.30504806 0.84609996 0.76341261 0.04203308]
 [0.38583424 0.59986902 0.19316829 0.75563258 0.04882688 0.03470886
  0.06642507 0.69179216 0.33265644 0.98527086]
 [0.80548264 0.70092578 0.95288125 0.59668787 0.52042094 0.4798909
  0.31150715 0.54511821 0.75965503 0.26256873]
 [0.37050654 0.24022513 0.56016124 0.4214604  0.5604078  0.08911058
  0.83140312 0.96144396 0.95390201 0.24528364]
 [0.56097578 0.56287663 0.09577622 0.12292495 0.72924813 0.08219106
  0.29710044 0.8839142  0.30372723 0.02789484]
 [0.05350392 0.66452969 0.084597   0.34688827 0.0665385  0.79017712
  0.28069173 0.31369764 0.59647843 0.6447783 ]
 [0.41343491 0.89532648 0.78195211 0.57132547 0.45947824 0.50921157
  0.25914991 0.89361056 0.0430653  0.4981274 ]
 [0.08793025 0.45074372 0.88247824 0.77801926 0.60716808 0.

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [49]:
random_matrix = np.random.rand(5, 5)
row_max = np.max(random_matrix, axis=1)
row_min = np.min(random_matrix, axis=1)
result_matrix = np.hstack((random_matrix, row_max[:, np.newaxis], row_min[:, np.newaxis]))


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  

In [56]:
import numpy as np

vector = np.arange(1, 52)

odd_numbers = vector[vector % 2 != 0]
even_numbers = vector[vector % 2 == 0]
odd_matrix = odd_numbers[:25].reshape(5, 5)
even_matrix = even_numbers[:25].reshape(5, 5)

product_matrix = np.dot(odd_matrix, even_matrix)

if np.linalg.det(product_matrix) != 0:
    inverse_matrix = np.linalg.inv(product_matrix)
    print("Обратная матрица:", inverse_matrix)
else:
    print("Обратная матрица не существует, так как определитель равен 0.")



Обратная матрица: [[-2.46855905e+11  2.33980583e-01 -9.47926674e+11  2.88327697e+12
  -1.68849439e+12]
 [ 1.63744459e+14  5.47775000e+01 -5.30898183e+14  4.06818531e+14
  -3.96648068e+13]
 [-3.24610577e+14  2.81474977e+14  3.52273250e+14 -2.50529121e+14
  -5.86085289e+13]
 [ 1.58975203e+14 -5.62949953e+14  8.91939755e+14 -7.30930459e+14
   2.42965456e+14]
 [ 2.13777213e+12  2.81474977e+14 -7.12366895e+14  5.71757772e+14
  -1.43003626e+14]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [58]:
chessboard = np.zeros((8, 8), dtype=int)

chessboard[1::2, ::2] = 1 
chessboard[::2, 1::2] = 1

print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
